### PR TITLE
Ensure students are added to group for EditCommand

### LINKED ISSUE #240: Allocations using the "edit" command does not actually add student to the Group's students
Steps to reproduce
1. `add group -g Test`
2. `edit 1 -g Test`
3. `show -g `Test`

Expected 
- The student at index 1 will be displayed as one of the group's students

Actual
- Group is empty

### PR DESCRIPTION
**Pull request by ganhongyao**
Fixes #240 

To test
1. add group -g Test
2. edit 1 -g Test
3. show -g Test`
4. check that the group `Test` contains the student.

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -115,11 +115,14 @@ public void addStudent(Student s) {
...
         requireNonNull(editedStudent);
 
+        // ID has changed, update IDs in assessments
         if (!target.getId().equals(editedStudent.getId())) {
             assessments.replaceStudent(target, editedStudent);
-            groups.replaceStudent(target, editedStudent);
         }
 
+        // Update group memberships
+        groups.replaceStudent(target, editedStudent);
```
Comment (ganhongyao) [inline src/main/java/seedu/address/model/AddressBook.java:124]: `replaceStudent` here removes all the student from all existing groups, then adds the student into the new groups. This should be done even when the ID did not change. If not, changes in group memberships are never updated.

File: src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java [hunk 2]
```diff
@@ -48,12 +48,16 @@ public void execute_addAllocByName_success() {
...
+
+        Group simpleGroupCopy = new Group(simpleGroup.name);
         model.addGroup(simpleGroup);
+        expectedModel.addGroup(simpleGroupCopy);
 
         Student expectedAmy = new PersonBuilder(simpleAmy)
                 .withGroups(VALID_GROUP_TUTORIAL).build();
 
-        Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()), new UserPrefs());
         expectedModel.setStudent(simpleAmy, expectedAmy);
```
Comment (ganhongyao) [inline src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java:61]: Tests are changed here. A copy of the group is created, if not when we do `expectedModel.setStudent(simpleAmy, expectedAmy);`, it adds the student to the group and the command cannot be executed since the student already exists in the group.

Comment (leonghongfai) [reply src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java:61]: Yeah this makes sense.

**Review by leonghongfai — APPROVED** [review]
Tested and works as per intended
