### PR TITLE
Fix command with no prefix error message bug

### LINKED ISSUE #122: Wrong error message displayed when no prefixes are inputted
### Description
When no prefixes are passed to commands, the error message displayed is not correct

### Steps to reproduce
1. Open the app.
2. Type in the command "add student Bob" and press "Enter".

### Expected behaviour
Error message of invalid command format displayed i.e. `Invalid command format! ...`.

### Actual behaviour
Error message of unknown command displayed i.e. `Unknown command`.

### Cause
`AddressBookParser::extractFullCommandWord` takes the command word(s) to be everything up till the first `-` (dash), and thus when no prefixes are present, it takes the full user input as the command words. Since "add student Bob" does not match any commands, it displays unknown command message.

To fix after v1.2b?

### PR DESCRIPTION
**Pull request by leonghongfai**
fixes #122

### CODE REVIEW

**Comment by leonghongfai** [comment]
lines 141 -145 if you can think of a better way to do it highly suggest it be changed

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -98,6 +78,36 @@ public Command parseCommand(String userInput) throws ParseException {
...
+        boolean isTwoWordCommand = arguments.length() > 0
+                && !arguments.startsWith(" -") && !Character.isDigit(arguments.charAt(1));
+
+        if (isTwoWordCommand) {
+            commandWord = extractFullCommandWord(commandWord, arguments);
+            arguments = extractArguments(arguments);
+        } else {
+            throw new ParseException(MESSAGE_UNKNOWN_COMMAND);
+        }
+
```
Comment (ganhongyao) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java]: Should we do this check within the `default` case in the `parseCommand` method above? So this method will only take in valid two word commands and is only responsible for returning the correct parser.

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 2]
```diff
@@ -127,8 +137,11 @@ private String extractArguments(String arguments) {
      */
     private String extractFullCommandWord(String firstCommandWord, String arguments) {
         int argumentsIndex = arguments.indexOf("-");
+        //TODO: if someone can make this look prettier please do so!
```
Comment (ganhongyao) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java]: I think we can remove this comment since the code is quite alright and I don't think we will ever come back to it even with the TODO

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java (hunk 1 above)
Comment (leonghongfai) [reply src/main/java/seedu/address/logic/parser/AddressBookParser.java]: Yeah that makes sense. Do merge  if the changes are what u were intending to see

**Comment by ganhongyao** [comment]
LGTM

**Comment by ganhongyao** [comment]
I think will be good to add tests if you have time too, but let's just merge this in first
