### PR TITLE
Show student card to resolve naming conflicts

### LINKED ISSUE #163: As a CS1101S professor, I can view the ID of students with the same name when failing to execute a command
... so that I don't need to input a show command to get the ID of students with the same name

### PR DESCRIPTION
**Pull request by leonghongfai**
closes #163 
The testing part please do take a look, I am not sure if this might be the best way to test for it. The current assertCommandFailure will always result in a failed test as it does not account for the FilteredList change.

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -173,6 +173,27 @@ public static void assertCommandFailure(Command command, Model actualModel, Stri
...
+     */
+    public static void assertCommandFailureWithFilteredListChange(Command command, Model actualModel,
+                                                                  String expectedMessage, List<Student> expectedList) {
+        AddressBook expectedAddressBook = new AddressBook(actualModel.getAddressBook());
+        List<Student> expectedFilteredList = expectedList;
+
+        assertThrows(CommandException.class, expectedMessage, () -> command.execute(actualModel));
+        assertEquals(expectedAddressBook, actualModel.getAddressBook());
+        assertEquals(expectedFilteredList, actualModel.getFilteredStudentList());
+    }
```
Comment (nbvannhi) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: I would suggest creating an assertion method similar to `assertCommandSuccess`, such as
```java
assertCommandFailure(Command command, Model actualModel, String expectedMessage, Model expectedModel)
```
This would allow **integration testing** together with the current unit testing. Perhaps taking a look at `assertCommandSuccess` to follow the convention would be a good idea.

File: src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java [hunk 2]
```diff
@@ -126,7 +130,11 @@ public void execute_duplicateStudentName_failure() {
 
         String expectedMessage = AddAllocCommand.MESSAGE_DUPLICATE_STUDENT_NAME;
 
-        assertCommandFailure(addAllocCommand, model, expectedMessage);
+        List<Student> expectedList = new ArrayList<>();
+        expectedList.add(simpleAmy);
+        expectedList.add(duplicateAmy);
+
+        assertCommandFailureWithFilteredListChange(addAllocCommand, model, expectedMessage, expectedList);
```
Comment (nbvannhi) [inline src/test/java/seedu/address/logic/commands/AddAllocCommandTest.java]: Wouldn't it be better to also cover **integration testing**? To be more specific, you can create a `Model` and **manually execute** the command on it (i.e., edit the filtered student list), then assert by comparing the two models with

```java
assertCommandFailure(Command command, Model actualModel, String expectedMessage, Model expectedModel)
```

I suggest taking a look at the `execute_addAllocByName_success()` to get a better idea :) Same for `AddScoreCommandTest` and `AddGroupCommandTest`

File: src/main/java/seedu/address/commons/util/SameNameConflictUtil.java [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+import java.util.function.Predicate;
+
+import seedu.address.model.Model;
+import seedu.address.model.student.IdContainsKeywordsPredicate;
+import seedu.address.model.student.Student;
+
+/**
+ * A container for Student name conflicts utility functions
+ */
+public class SameNameConflictUtil {
```
Comment (nbvannhi) [inline src/main/java/seedu/address/commons/util/SameNameConflictUtil.java]: Hmm idt it's necessary to create a new class for only one method 🤔
Can refer to my suggested approach in `AddAllocCommand`!

File: src/main/java/seedu/address/logic/commands/AddAllocCommand.java [hunk 4]
```diff
@@ -75,6 +76,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         if (studentsToEdit.size() > 1) {
+            showStudentsWithNameConflicts(model, studentsToEdit);
```
Comment (nbvannhi) [inline src/main/java/seedu/address/logic/commands/AddAllocCommand.java]: Maybe this will do

```suggestion
            List<String> matchedIds = matchedStudents.stream()
                                    .map(Student::getId).map(ID::getValue)
                                    .collect(Collectors.toList());
            Predicate<Student> predicate = new IdContainsKeywordsPredicate(matchedIds);
            model.updateFilteredStudentList(predicate);
```

Same for `AddScoreCommand` and `AddGroupCommand`

File: src/main/java/seedu/address/commons/util/SameNameConflictUtil.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+     */
+    public static void showStudentsWithNameConflicts(Model model, List<Student> matchedStudents) {
+        List<String> keywordsList = new ArrayList<>();
+        for (Student student : matchedStudents) {
+            String studentId = student.getId().getValue();
+            if (!keywordsList.contains(studentId)) {
+                keywordsList.add(studentId);
+            }
+        }
+        Predicate predicate = new IdContainsKeywordsPredicate(keywordsList);
```
Comment (nbvannhi) [inline src/main/java/seedu/address/commons/util/SameNameConflictUtil.java]: Not really related but be careful not to use raw type :) Can put `Predicate<Student>` instead

**Review by nbvannhi — CHANGES_REQUESTED** [review]
Perhaps showing students with duplicate naming can be done within the `execute` method itself, instead of creating a new util class just for one method.

W.r.t. testing, I think it is correct but can improve to also cover integration testing.

Good job overall!

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 1 above)
Comment (leonghongfai) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: The problem with following the assertCommandSuccess model is the filtered list check. To get the correct filtered list, I am basically doing the same thing to the expected model as i did with the actual model, which I don't think makes a lot of sense. It's like making the same model twice and comparing them. Thats why i made a new method which takes in a filteredlist as input, so I can check the actual filteredlist versus what I know should be the correct filtered list

File: src/main/java/seedu/address/commons/util/SameNameConflictUtil.java (hunk 3 above)
Comment (leonghongfai) [reply src/main/java/seedu/address/commons/util/SameNameConflictUtil.java]: Im not sure how the group came to the conlusion to put this method under util actually. But I agree that it can be done under each respective command.

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 1 above)
Comment (nbvannhi) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: I suppose the task of filtering the list is done within the command itself? In other words, after the command is executed the model's filtered list will be updated accordingly.

File: src/main/java/seedu/address/logic/commands/AddAllocCommand.java (hunk 4 above)
Comment (ganhongyao) [reply src/main/java/seedu/address/logic/commands/AddAllocCommand.java]: Sorry I didn't comment on this earlier, but I think what Vani suggested here may be a better approach than `SameNameConflictUtil::showStudentsWithNameConflicts`, since we're kind of doing too many things at once within that method.

On top of that, while I was working on #173, I think instead of creating a `Predicate` from the IDs of the matched students, would it be better to have a `NameEqualsPredicate` with the name argument that the user passed, then calling `model.updateFilteredStudentList` with that predicate? I feel like that's more natural

What do you guys think? @nbvannhi @leonghongfai

Comment (leonghongfai) [reply src/main/java/seedu/address/logic/commands/AddAllocCommand.java]: @ganhongyao @nbvannhi I think its more natural too, I only did it via IDs as the `NameContainsKeywordsPredicate` is unable to match the whole name fully. If we are fully agreeable, I can change it accordingly.

Comment (nbvannhi) [reply src/main/java/seedu/address/logic/commands/AddAllocCommand.java]: I agree too 👍🏻

**Review by nbvannhi — APPROVED** [review]
LGTM 👍🏻
